import {
  TargetPlan,
  MetricActual,
  CoachTask,
  DailyCoachBrief,
} from '../types';
import {
  calculateGrowthRate,
  generateMonthlyTargets,
  applyGrowthCurve,
  generateDailyTargets,
  generateWeeklyTargets,
} from '../services/targetCalculator';

/**
 * DEMO MODE SEED DATA
 * ===================
 * IMPORTANT: All demo data is marked with isDemo=true.
 * In production, this data must be excluded from real metrics.
 * The DEMO_MODE=true flag should only be enableable in development.
 */

export const DEMO_TARGET_PLAN: TargetPlan = {
  id: 'demo-target-plan-001',
  name: '12-Month Growth Plan (Demo)',
  startMonth: 1,
  startYear: 2026,
  endMonth: 12,
  endYear: 2026,
  startPieces: 13, // Month 1 target
  endDailyPieces: 12.9, // End of year daily target
  growthCurve: 'geometric',
  growthRate: 1.36, // ~36% month-over-month growth
  weekdayWeights: {
    sunday: 0.8,
    monday: 1.0,
    tuesday: 1.0,
    wednesday: 1.0,
    thursday: 1.0,
    friday: 1.2,
    saturday: 1.2,
  },
  yearlyTarget: {
    pieces: 1355, // Sum of monthly targets
    orders: 1042,
    revenue: 37934000, // ~379,340 EUR in cents
    sessions: 90333,
    visitors: 66910,
  },
  monthlyTargets: [],
  weeklyTargets: [],
  dailyTargets: [],
  catalogTarget: {
    totalProductsByDate: '2026-12-31',
    targetCount: 100,
    currentCount: 24,
  },
  isActive: true,
  createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  updatedAt: new Date().toISOString(),
  version: 1,
  changeHistory: [
    {
      version: 1,
      changedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      changedBy: 'demo-owner',
      reason: 'Initial target plan created',
      changes: {
        startPieces: 13,
        endDailyPieces: 12.9,
      },
    },
  ],
};

// Generate the full target plan
const growthRate = calculateGrowthRate(13, 12.9, 12);
const baseMonthlyTargets = generateMonthlyTargets(13, growthRate, 12, 2026, 1);
DEMO_TARGET_PLAN.monthlyTargets = applyGrowthCurve(baseMonthlyTargets, 'geometric');
DEMO_TARGET_PLAN.dailyTargets = generateDailyTargets(DEMO_TARGET_PLAN.monthlyTargets, DEMO_TARGET_PLAN.weekdayWeights);
DEMO_TARGET_PLAN.weeklyTargets = generateWeeklyTargets(DEMO_TARGET_PLAN.dailyTargets);

/**
 * Generate 30 days of demo metric actuals
 * These are marked with isDemo=true and should be excluded from production metrics
 */
export const DEMO_METRIC_ACTUALS: MetricActual[] = Array.from({ length: 30 }, (_, i) => {
  const d = new Date(Date.now() - (29 - i) * 86400000);
  const dateStr = d.toISOString().split('T')[0];
  const isWeekend = d.getDay() === 0 || d.getDay() === 6;

  // Match targets with some variance
  const targetForDay = DEMO_TARGET_PLAN.dailyTargets.find((dt) => dt.date === dateStr);
  const targetPieces = targetForDay?.piecesTarget || 0;

  // Generate realistic actuals with variance
  const variance = 0.7 + Math.random() * 0.6; // 70-130% of target
  const piecesSold = Math.round(targetPieces * variance);
  const orders = Math.round(piecesSold / 1.3);
  const aov = 280 + Math.round((Math.random() - 0.5) * 50);
  const revenue = orders * aov * 100; // Convert to cents
  const visitors = Math.round(targetPieces / 0.015 / 1.35 * variance);
  const sessions = Math.round(visitors * 1.35);
  const conversionRate = piecesSold > 0 ? piecesSold / sessions : 0.015;

  return {
    id: `metric-${dateStr}`,
    date: dateStr,
    piecesSold,
    orders,
    revenue,
    grossProfit: Math.round(revenue * 0.45), // 45% margin
    sessions,
    visitors,
    conversionRate: Math.round(conversionRate * 1000) / 10,
    aov: aov * 100,
    unitsPerOrder: piecesSold > 0 ? Math.round((piecesSold / orders) * 10) / 10 : 1.3,
    newCustomers: Math.round(orders * 0.7),
    returningCustomers: Math.round(orders * 0.3),
    repeatRate: 0.15,
    emailSubscribers: Math.round(piecesSold * 0.5),
    waitlistSignups: Math.round(Math.random() * 5),
    contentPostsPublished: i % 3 === 0 ? 1 : 0,
    adSpend: Math.round(revenue * 0.2), // 20% of revenue
    roas: 3.0 + Math.random() * 0.5,
    returns: Math.round(orders * 0.05),
    refunds: Math.round(revenue * 0.02),
    stockSellThrough: 65 + Math.round(Math.random() * 20),
    productsListed: 24 + Math.floor(i / 5),
    productsPhotographed: 24 + Math.floor(i / 5),
    isDemo: true, // DEMO FLAG - CRITICAL
  };
});

/**
 * Generate demo coach tasks for today
 */
export const DEMO_COACH_TASKS: CoachTask[] = [
  {
    id: 'demo-task-001',
    date: new Date().toISOString().split('T')[0],
    title: 'List 3 new products today',
    family: 'catalog',
    status: 'pending',
    priority: 'high',
    reason: 'Catalog target: 76 products remaining to reach 100 by 2026-12-31',
    expectedImpact: {
      pieces: 2,
      description: '+1-2 pieces from new product visibility',
    },
    effortMinutes: 45,
    deepLink: { type: 'product', targetId: 'new' },
    autoGenerated: true,
    position: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-002',
    date: new Date().toISOString().split('T')[0],
    title: 'Ship 5 orders before 14:00',
    family: 'operations',
    status: 'pending',
    priority: 'high',
    reason: '5 orders ready for fulfilment',
    expectedImpact: {
      description: 'Maintain shipping SLA and customer satisfaction',
    },
    effortMinutes: 50,
    deepLink: { type: 'order', targetId: 'pending' },
    autoGenerated: true,
    position: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-003',
    date: new Date().toISOString().split('T')[0],
    title: 'Publish 1 Instagram post about Nº 001 Merino Coat',
    family: 'content',
    status: 'pending',
    priority: 'medium',
    reason: 'Content target: 2 posts remaining this week',
    expectedImpact: {
      description: '+5-10% traffic from social channels',
    },
    effortMinutes: 30,
    deepLink: { type: 'campaign', targetId: 'social' },
    autoGenerated: true,
    position: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-004',
    date: new Date().toISOString().split('T')[0],
    title: 'Review low-converting product Nº 012',
    family: 'conversion',
    status: 'pending',
    priority: 'medium',
    reason: 'Product has 340 views but only 2 sales (0.6% conversion vs 1.5% benchmark)',
    expectedImpact: {
      pieces: 3,
      description: '+2-3 pieces if conversion improves to benchmark',
    },
    effortMinutes: 20,
    deepLink: { type: 'product', targetId: 'prod-12' },
    autoGenerated: true,
    position: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-task-005',
    date: new Date().toISOString().split('T')[0],
    title: 'Answer 3 unanswered customer messages',
    family: 'customer_service',
    status: 'pending',
    priority: 'high',
    reason: '3 messages in inbox older than 2 hours',
    expectedImpact: {
      description: 'Improve customer satisfaction and conversion',
    },
    effortMinutes: 15,
    deepLink: { type: 'customer', targetId: 'inbox' },
    autoGenerated: true,
    position: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

/**
 * Generate demo daily coach brief for today
 */
export const DEMO_DAILY_COACH_BRIEF: DailyCoachBrief = {
  date: new Date().toISOString().split('T')[0],
  target: {
    pieces: DEMO_TARGET_PLAN.dailyTargets.find((d) => d.date === new Date().toISOString().split('T')[0])?.piecesTarget || 13,
    orders: 10,
    revenue: 280000, // 2,800 EUR in cents
  },
  actual: {
    pieces: 8,
    orders: 6,
    revenue: 168000, // 1,680 EUR in cents
  },
  pace: 'behind',
  gap: 5,
  probabilityOfHitting: 65,
  tasks: DEMO_COACH_TASKS,
  totalEffortMinutes: 160,
  topPriorities: ['demo-task-001', 'demo-task-002', 'demo-task-005'],
  riskPanel: [
    {
      type: 'stock_out',
      severity: 'high',
      message: 'Nº 001 size S will sell out in 2 days at current rate',
      targetId: 'prod-01',
    },
    {
      type: 'late_shipment',
      severity: 'medium',
      message: '2 orders past 24h shipping SLA',
    },
  ],
  opportunityPanel: [
    {
      type: 'trending_product',
      message: 'Nº 004 Wool Coat views up 45% this week',
      targetId: 'prod-04',
    },
    {
      type: 'returning_visitor',
      message: '12 returning visitors browsing archive today',
    },
  ],
  winsPanel: [
    {
      type: 'milestone',
      message: 'First 100 pieces sold this month!',
    },
  ],
  dailyScore: 0,
  streak: 3,
  carryOverCount: 0,
  generatedAt: new Date().toISOString(),
};

/**
 * Seed the targets system with demo data
 * This should only be called when DEMO_MODE=true
 */
export async function seedTargetsSystem(): Promise<{ success: boolean; message: string }> {
  try {
    const { saveTargetPlan } = await import('../supabase/targetsService');
    const { saveMetricActual } = await import('../supabase/targetsService');
    const { saveCoachTask } = await import('../supabase/targetsService');
    const { saveDailyCoachBrief } = await import('../supabase/targetsService');

    // Save target plan
    await saveTargetPlan(DEMO_TARGET_PLAN);

    // Save metric actuals
    for (const actual of DEMO_METRIC_ACTUALS) {
      await saveMetricActual(actual);
    }

    // Save coach tasks
    for (const task of DEMO_COACH_TASKS) {
      await saveCoachTask(task);
    }

    // Save daily coach brief
    await saveDailyCoachBrief(DEMO_DAILY_COACH_BRIEF);

    return {
      success: true,
      message: 'Targets system seeded with demo data (isDemo=true). DO NOT use in production.',
    };
  } catch (error) {
    console.error('Error seeding targets system:', error);
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Failed to seed targets system',
    };
  }
}
